name: Generate Datas

on:
  workflow_dispatch: # execute manually
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

jobs:
  summary-cards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}

  metrics-achievements:
    runs-on: ubuntu-latest
    steps:
      - name: Achievements metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B # Display achievements with rank B or higher
          plugin_achievements_secrets: yes # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut # Hide octonaut achievement
          plugin_achievements_limit: 0 # Display all unlocked achievement matching threshold and secrets params

  metrics-github:
    runs-on: ubuntu-latest
    steps:
      - name: Github metrics
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
